# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1cbaa98259d70acb22a31a48386d95e95252633c39933e720dc1d692622f64c5d57c4540140ecfeebac1adbc4250057c44a77e2786981672567a026a0927e4bc

test:
  secret_key_base: 14e8e3332fd028b5f159531a0538e3bdfd214e32fc0ca006f58a0168893c084c52d3f8cd3e4c307dd585299407236c920db35c20da16a2fc9e55607711135825

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
